# Generated by Django 5.0.1 on 2024-01-16 20:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('description', models.TextField(max_length=1000)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('login', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Change',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('item', models.CharField(max_length=255)),
                ('change_type', models.CharField(choices=[('a', 'added'), ('d', 'deleted'), ('m', 'modified')], max_length=1)),
                ('milestone_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vcs.milestone')),
                ('repo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vcs.repository')),
            ],
        ),
        migrations.AddField(
            model_name='repository',
            name='author_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vcs.user'),
        ),
        migrations.AddField(
            model_name='milestone',
            name='author_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vcs.user'),
        ),
        migrations.CreateModel(
            name='UserRepo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('repo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vcs.repository')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vcs.user')),
            ],
        ),
    ]
